# Generated by Django 6.0.7 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("devices", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alert_type", models.CharField(choices=[("NEW_DEVICE", "New Device"), ("DEVICE_OFFLINE", "Device Offline"), ("MAC_CHANGED", "MAC Changed")], max_length=30)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="devices.device")),
            ],
        ),
    ]
