# Generated by Django 6.0.7 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("mac_address", models.CharField(max_length=17, unique=True)),
                ("vendor", models.CharField(blank=True, max_length=255)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("trusted", models.BooleanField(default=False)),
                ("online", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
