# Generated by Django 6.0.7 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("devices", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"), ("computer", "Computer"),
                    ("phone", "Phone"), ("tablet", "Tablet"),
                    ("router", "Router"), ("printer", "Printer"),
                    ("camera", "Camera"), ("smart_home", "Smart-home device"),
                    ("other", "Other"),
                ],
                default="unknown",
                max_length=30,
            ),
        ),
    ]
