# Generated by Django 6.0.7 on 2026-07-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_add_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
