# Generated by Django 6.0.7 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonitoringSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("auto_scan_enabled", models.BooleanField(default=False)),
                ("scan_interval_seconds", models.PositiveIntegerField(default=60)),
                ("last_scan_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
